### ISSUE TITLE
CPF data-download server Error (500)

### ISSUE THREAD

**Issue by PA7T** [GorgiAstro/laser-orbit-determination#1]
Dear Clément,

Thanks for the very explanatory tutorial on laser-orbit-determination!
One thing that I am struggling with, is the "Downloading and parsing CPF data".

Executing:

> cpfList = queryCpfData(username_edc, password_edc, url, 
>                        sat_list[sc_name]['cospar_id'], startCollectionDate - timedelta(days=1))
> display(cpfList)

list a valid and available CPF file, but

> cpfDataFrame = dlAndParseCpfData(username_edc, password_edc, url, 
>                                  [cpfList.index[0]], # If several ephemerides are available for this day, only take the first
>                                  startCollectionDate - timedelta(days=1),
>                                  odDate + timedelta(days=1))

throws a Server Error 500.

Reading the EDC-API, I do not understand how one can query a CPF file via the call you are using.
Is there something I missed?

Thanks a lot for your help!

Cheers,

DL2ZZ

**Comment by bubufatty** [comment]
Dear PA7T:

I made a minor modification on these codes to parse the local data, 
by replacing the corresponding on-line version:

`# Requesting CPF data`
`from localdata import LocalCPF`
`cpf_start = startCollectionDate - timedelta (days = 1)`
`cpf_end = odDate + timedelta (days = 1)`
`cpfDataFrame, dt = LocalCPF(sc_name, CPFfile, cpf_start, cpf_end, dt)`

it will read the local CPF data saved in './cpf/' folder.
Hope this can help you understanding how Clement's example runs.

[localdata.zip](https://github.com/GorgiAstro/laser-orbit-determination/files/5908626/localdata.zip)

**Comment by PA7T** [comment]
Dear bubufatty:

Thanks! I will try it.
